name: bic_numbers_scraper
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - ipykernel
  - pandas
  - pandas-profiling
  - numpy
  - requests
  - pip:
      - beautifulsoup4
      - selenium
      - lxlm
      - jupyter_black
